
odom_frame_id:    odom
odom_model_type:  diff-corrected
odom_alpha1:      0.2
odom_alpha2:      0.2
odom_alpha3:      0.2
odom_alpha4:      0.2
#odom_alpha4:     0.2

base_frame_id:    robot_footprint
global_frame_id:  map

min_particles:    30
max_particles:    300

initial_pose_x:   0.0
initial_pose_y:   0.0
initial_pose_z:   0.0

laser_model_type: likelihood_field
laser_z_hit:      0.95
laser_z_rand:     0.05