
odom_frame_id:    odom
odom_model_type:  diff-corrected

base_frame_id:    robot_footprint
global_frame_id:  map

min_particles:    500
max_particles:    5000

initial_pose_x:   0.0
initial_pose_y:   0.0
initial_pose_z:   0.0

laser_model_type: likelihood_field
laser_z_hit:      0.95
laser_z_rand:     0.05