global_costmap:
   global_frame:      map
   robot_base_frame:  robot_footprint
   update_frequency:  15.0
   publish_frequency: 15.0
   width:             40.0
   height:            40.0
   resolution:        0.02
   origin_x:          -38.560000
   origin_y:          -30.240000
   static_map:        true
   rolling_window:    false